### ISSUE TITLE
the implementation of Silhouette

### ISSUE THREAD

**Issue by autosquid** [avanindra/EPVH#2]
Hi, I am checking the code, but I could not find the implementation of the `Silhouette` class. Would you kindly push it, so I can do some fix to the existing code. (to remove compilation errors.)

**Comment by avanindra** [comment]
Yes , I will push it. The silhouette class was more or less related to grabcut output of opencv. It can be removed altogether , as main algorithm eventually uses only contours with sequence of 2d points in anticlockwise for foreground and clockwise for background.

But for now I will push silhouette class.

**Comment by autosquid** [comment]
Glad the code compiles. And I can see the hints of Grabcut in `silhouette`. : )
