### ISSUE TITLE
Vector and Point data structure

### ISSUE THREAD

**Issue by autosquid** [avanindra/EPVH#3]
Hi, it is me again.

It looks like you are trying to replace `cv::Point(2f)` with `Eigen::Vector2d` .  Am I right?

So the `Eigen::Vector` will be the final representation for all  vectors and points?

**Comment by avanindra** [comment]
Yes , I am switching to to eigen for all the 2d and 3d ( basically for intersections and line clipping ) calculations.  Although occasionally exact arithmetic is needed when primitives ( points , lines , planes ) , become too close to each other. May be later on , cgal kernels could be used for exact computations.

**Comment by autosquid** [comment]
Nice work. I made a few fixes, but then found you have completely fixed the `Point` `Vector` problems. Really amzing
