### ISSUE TITLE
How to generate the data in alien-contour.txt

### ISSUE THREAD

**Issue by wanglcore** [avanindra/EPVH#9]
Hi @avanindra,

I'v already gone through the demo code and now I want to implement this demo on my own image.
Here's my problem:
I really don't know how to generate the data like data in the alien-contour.txt. Is there any methods or functions to generate them in this git?
I'll really appreciate it if I got your reply!

Thank you very much!

**Comment by avanindra** [comment]
Hi @wanglcore 

First, sorry I missed to see your message. Hence replying quite late.

You can supply your silouette contours as double vectors of 2d points std::vector< std::vector< Eigen::Vector2d > >.

If the sequence is counter clockwise it as object countour , while is it anti clockwise it is hole. Each one dim array in the 2d array is treated as single connected consistent contour.

As to generate the contours , you can use OpenCV's findContours on thresholded photos (binary, black and white). To generate the segmentation you can use methods such as Grabcut. Also note that the each photo should be calibrated and aligned i.e. it's camera matrix should be known , then only you can compute the visual hull.
